all:
  hosts:
    prod:
      primary_host: tiddlyhost.com
      tiddlyspot_host: tiddlyspot.com
      ansible_host: "{{ primary_host }}"
      #ansible_host: tiddlyhub.com
      ansible_user: fedora
      # For letsencrypt
      cert_hosts:
      - "{{ primary_host }}"
      - "{{ tiddlyspot_host }}"

    #prod_new:
    #  # (Not the original intended purpose of this domain name but never mind)
    #  primary_host: tiddlyhub.com
    #  tiddlyspot_host: ~
    #  ansible_host: "{{ primary_host }}"
    #  ansible_user: fedora
    #  # For letsencrypt
    #  cert_hosts:
    #  - "{{ primary_host }}"

  vars:
    root_home_dir: /root
    home_dir: /home/{{ ansible_user }}

    bin_dir: "{{ home_dir }}/bin"
    docker_dir: "{{ home_dir }}/docker"
    backups_dir: "{{ home_dir }}/backups"
    db_dump_file: "{{ backups_dir }}/dbdump.gz"

    prerelease_empty: https://tiddlywiki.com/prerelease/empty.html
