#
# Builds the Tiddlyhost container image and pushes it.
# Also runs the test suite using the base container image.
#
name: Build

on:
  workflow_dispatch:

env:
  USER_ID: 1000

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # See https://github.com/actions/checkout/pull/1067
        # Switch back to the standard default in future when that gets merged.
        uses: simonbaird/checkout@no-progress-option
        #uses: actions/checkout@v3
        with:
          show-progress: false
          fetch-depth: 0

      - name: Build base image
        run: make fast-build-base

      - name: Setup rails
        run: make rails-init-ci

      - name: Run tests
        run: make test-ci

      - name: Build main image
        run: make build-prod-ci

      - name: Push image to docker hub
        run: |
          echo ${{ secrets.DOCKER_PUSH_TOKEN }} | docker login --username ${{ secrets.DOCKER_PUSH_USER }} --password-stdin
          docker push sbaird/tiddlyhost
